name: 'build devcontainer image'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3